### ISSUE TITLE
Containers: TODO

### ISSUE THREAD

**Issue by lmperry** [vistalab/docker#1]
DOCKER CONTAINERS:
- [ ] Co-reg: this might actually be done through Matlab scripts that exist in Vistasoft.
- [ ] Tissue segmentation 
- [ ] Ac-pc alignment
- [ ] Cortical mesh generation
- [ ] Quench in Docker
- [ ] ITK-Gray in Docker
- [ ] PRF Fit
- [ ] LIFE
- [ ] MRTRIX
- [ ] MRQ
- [ ] QA for *

**Comment by mezera** [comment]
Long list. What does in mean?
No AFQ?

**Comment by lmperry** [comment]
@mezera: We are looking to hire in the new year and this is a list of things related to that. These are some containers we'd like the new hire to build and skills we'd like them to have. 

I have already containerized AFQ. Once I finish the documentation I will push it to this repo.

**Comment by lmperry** [comment]
Tracked elsewhere.
